# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
  # Stripe.setPublishableKey()

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bc61dbf94ad8f07f2e02ea22b4657b7382af502245c71edfe7207dde18748e1adc475d61826d0524e8268e5750289053b64ada8a944bf4f3e3490ba7e311e01
  # dna_map: 74a87cd10f42792e12b5d25d798e67bc468bcd18d3e7cbbbb0e7b05d66d1e4e1e1c127312357877c90d7686f9431ff09974377dc4ecc90c749eddce04604a0e7
  dna_map: <%= ENV["DNA_STAFF_API"] %>

test:
  secret_key_base: 6bc61dbf94ad8f07f2e019907554657b7382af502245c71edfe7207dde18748e1adc475d61826d0524e8268e5750289053b64ada8a944bf4f3e3490ba7e311e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  my_secret_token: <%= ENV["MY_SECRET_TOKEN"] %>
  dna_map: <%= ENV["DNA_STAFF_API"] %>
